######################################################################
# Automatically generated by qmake (2.00a) Pzt Eyl 18 10:59:04 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += sozluq.h
SOURCES += main.cpp sozluq.cpp
